### ISSUE TITLE
建议可以多点api，比如回调事件多点，由自己配选项

### ISSUE THREAD

**Issue by az8321550** [nimojs/paging#2]
建议可以多点api，比如回调事件多点，由自己配选项

**Comment by nimojs** [comment]
感谢反馈
你指的是什么时机的触发回调事件？需要解决什么样的业务需求？

**Comment by az8321550** [comment]
比如点击按钮后的回调事件，
ajax前
ajax后
等等这些
为了满足各种各样的业务需求

**Comment by nimojs** [comment]
请看这个页面
[AJAX无刷新分页](http://spmjs.io/docs/paging/latest/examples/ajax.html)

### 点击按钮后的回调
```js
$view.on('click', 'a.ui-paging-item,a.ui-paging-next,a.ui-paging-prev', function () {
    var $this = $(this);
    var page = $this.attr('href')
    goto(page)
    return false
})
```

### ajax前后

```js
var goto = function (page) {
    $.ajax({
        url:'data.json',
        type: 'get',
        dataType: 'json'
    }).done(function (data) {
```

**Comment by nimojs** [comment]
## 关于回调函数
Paging 是基于 Mustache 模板引擎渲染生成 HTML 。通过编辑模板可以自由的控制生成的 HTML 结果。生成 HTML 以后可以自己给 DOM 绑定事件，打到点击回调等效果。

## 关于AJAX
与ajax的结合点在 [render(config)](http://spmjs.io/docs/paging/latest/docs/api.html#render-render-config)中的 `config.pageCount` `config.currentPage `。根据当前页面和总页数2个数字渲染出HTML

## 关于界面的定制
渲染的HTML是基于模板引擎的，所以编辑模板引擎可以达到任何想要的效果。[自定义界面](http://spmjs.io/docs/paging/latest/examples/index.html) 

如果想用自己的模板引擎，可以只使用 `createData` 生成必要的数据,然后渲染出页面 [handlebars&createData](http://spmjs.io/docs/paging/latest/examples/handlebars.html)
